### ISSUE TITLE
Se517202@gmail.com 

### ISSUE THREAD

**Issue by Salm55** [Microsoft/azure-devops-wit-client-om-migration-guide#11]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/azure-devops-wit-client-om-migration-guide/issues/10
- [ ] https://github.com/microsoft/azure-devops-wit-client-om-migration-guide/pull/9
- [ ] https://github.com/microsoft/azure-devops-wit-client-om-migration-guide/pull/8
```
